"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { adminRequest, ArchiveButton } from "./controls";
import type { ProductInput } from "@/lib/admin/product-input";

export const emptyProduct: ProductInput = { version: 0, name: "", slug: "", brandId: null, categoryId: null, status: "DRAFT", wearable: false, price: "0.00", compareAtPrice: "", description: "", highlights: "", images: [], videoUrl: "", seoTitle: "", seoDescription: "", variants: [{ sku: "", size: "", price: "", quantity: 0, active: true }] };

export function ProductEditor({ initial, categories, brands }: { initial: ProductInput; categories: { id: number; name: string }[]; brands: { id: number; name: string }[] }) {
  const router = useRouter();
  const [form, setForm] = useState(initial);
  const [busy, setBusy] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const update = <K extends keyof ProductInput>(key: K, value: ProductInput[K]) => { setSaved(false); setForm((f) => ({ ...f, [key]: value })); };
  const setVariant = (index: number, patch: Partial<ProductInput["variants"][number]>) => update("variants", form.variants.map((v, i) => i === index ? { ...v, ...patch } : v));
  return <form onSubmit={async (event) => {
    event.preventDefault(); setError(""); setBusy(true); setSaved(false);
    try { const result = await adminRequest("products/save", form); setSaved(true); router.replace(`/admin/products/${result.id}?saved=1`); router.refresh(); }
    catch (error) { setError(error instanceof Error ? error.message : "Unable to save product."); } finally { setBusy(false); }
  }}><div className="admin-heading"><div><Link href="/admin/products" className="admin-back">← All products</Link><h1>{initial.id ? "Edit product" : "Add a product"}</h1><p>{initial.id ? "Keep your catalogue accurate and ready for the next ride." : "Good gear deserves a great introduction."}</p></div><div className="admin-heading-actions"><Link className="admin-button secondary" href="/admin/products">Cancel</Link><button className="admin-button" disabled={busy || uploading}>{busy ? "Saving…" : "Save product →"}</button></div></div>
    {error && <p className="admin-error" role="alert">{error}</p>}{saved && <p className="admin-success" role="status">Product saved.</p>}
    <div className="admin-editor-grid"><div className="admin-editor-main">
      <section className="admin-panel admin-form-panel"><div className="admin-section-title"><span>01</span><div><h2>Product information</h2><p>Give your product a name and a story.</p></div></div><label>Product name<input value={form.name} maxLength={255} required placeholder="e.g. Klim Carlsbad Adventure Jacket" onChange={(e) => { const name = e.target.value; update("name", name); if (!initial.id && (!form.slug || form.slug === form.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""))) update("slug", name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} /></label><label>URL slug<input value={form.slug} maxLength={191} pattern="[a-z0-9]+(-[a-z0-9]+)*" required onChange={(e) => update("slug", e.target.value)} /><small>/products/{form.slug || "your-product"}</small></label><label>Description<textarea value={form.description} rows={7} maxLength={30000} placeholder="What makes this product right for the ride?" onChange={(e) => update("description", e.target.value)} /></label><label>Key features<textarea value={form.highlights} rows={4} maxLength={10000} placeholder="One feature per line" onChange={(e) => update("highlights", e.target.value)} /></label></section>
      <section className="admin-panel admin-form-panel"><div className="admin-section-title"><span>02</span><div><h2>Product media</h2><p>The first image appears on product cards. Up to 12 images.</p></div></div><label className="admin-upload"><b>{uploading ? "Uploading…" : "＋ Upload a product image"}</b><span>JPG, PNG or WebP · Maximum 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading || form.images.length >= 12} onChange={async (event) => {
        const file = event.target.files?.[0]; if (!file) return;
        setUploading(true); setError(""); const body = new FormData(); body.set("image", file);
        try { const response = await fetch("/api/admin/upload", { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setForm((f) => ({ ...f, images: [...f.images, result.url] })); }
        catch (error) { setError(error instanceof Error ? error.message : "Upload failed."); } finally { setUploading(false); event.target.value = ""; }
      }} /></label><div className="admin-media-list">{form.images.map((url, index) => <div className="admin-media-row" key={index}><span>{index === 0 ? "Cover" : index + 1}</span><input aria-label={`Image ${index + 1} URL`} value={url} onChange={(e) => update("images", form.images.map((item, i) => i === index ? e.target.value : item))} placeholder="https://… or /images/…" /><button type="button" aria-label={`Move image ${index + 1} earlier`} disabled={index === 0} onClick={() => { const images = [...form.images]; [images[index - 1], images[index]] = [images[index], images[index - 1]]; update("images", images); }}>↑</button><button type="button" aria-label={`Remove image ${index + 1}`} onClick={() => update("images", form.images.filter((_, i) => i !== index))}>×</button></div>)}</div><button type="button" className="admin-text-button" disabled={form.images.length >= 12} onClick={() => update("images", [...form.images, ""])}>+ Add image by URL</button><label>Product video URL<input type="url" value={form.videoUrl} onChange={(e) => update("videoUrl", e.target.value)} placeholder="https://…/walkthrough.mp4" /><small>Direct MP4 or WebM video link.</small></label></section>
      <section className="admin-panel admin-form-panel">
        <div className="admin-section-title"><span>03</span><div><h2>Price & stock</h2><p>Enter your selling price and the number of items you have.</p></div></div>
        <label>Price (AUD)<input type="number" min="0" step="0.01" required value={form.price} onChange={(e) => update("price", e.target.value)} /></label>
        <details open={form.compareAtPrice ? true : undefined}><summary>Sale pricing (optional)</summary><label>Original price (AUD)<input type="number" min="0" step="0.01" value={form.compareAtPrice} onChange={(e) => update("compareAtPrice", e.target.value)} placeholder="Price before discount" /><small>Shown crossed out beside your selling price.</small></label></details>
        <label className="admin-checkbox"><input type="checkbox" checked={form.wearable} onChange={(e) => update("wearable", e.target.checked)} />This product comes in wearable sizes</label>
        {form.wearable && <p className="admin-muted">Add each size and its stock count. New sizes use the price above.</p>}
        {form.variants.map((v, index) => <div key={v.id ?? index} className={form.wearable || form.variants.length > 1 ? "admin-variant" : undefined}>
          {(form.wearable || form.variants.length > 1) && <div className="admin-variant-title"><strong>{form.wearable ? "Size " + (index + 1) : v.size || "Option " + (index + 1)}</strong>{!v.id && form.variants.length > 1 && <button type="button" onClick={() => update("variants", form.variants.filter((_, i) => i !== index))}>Remove</button>}</div>}
          <div className="admin-field-pair">
            {(form.wearable || form.variants.length > 1) && <label>{form.wearable ? "Size" : "Option name"}<input required={form.wearable} maxLength={50} value={v.size} placeholder={form.wearable ? "e.g. M, L, XL" : "e.g. Standard"} onChange={(e) => setVariant(index, { size: e.target.value })} /></label>}
            <label>On-hand stock<input type="number" min="0" max="1000000" step="1" required value={v.quantity} onChange={(e) => setVariant(index, { quantity: Number(e.target.value) })} /><small>Number of items currently in stock.</small></label>
          </div>
          {v.price !== "" && <p className="admin-muted">This saved option has its own price: AUD {v.price}. <button type="button" className="admin-text-button" onClick={() => setVariant(index, { price: "" })}>Use the product price</button></p>}
          {v.id && <details><summary>Stock reference & availability</summary><p>SKU: {v.sku}</p><label className="admin-checkbox"><input type="checkbox" checked={v.active} onChange={(e) => setVariant(index, { active: e.target.checked })} />Available for sale</label></details>}
        </div>)}
        {form.wearable && <button type="button" className="admin-text-button" disabled={form.variants.length >= 60} onClick={() => update("variants", [...form.variants, { sku: "", size: "", price: "", quantity: 0, active: true }])}>+ Add size</button>}
        <p className="admin-muted">A unique stock reference (SKU) is generated automatically when you save.</p>
      </section>
      <section className="admin-panel admin-form-panel"><div className="admin-section-title"><span>04</span><div><h2>Search engine listing</h2><p>Help riders find the right gear.</p></div></div><label>SEO title<input maxLength={255} value={form.seoTitle} onChange={(e) => update("seoTitle", e.target.value)} placeholder={form.name || "Defaults to product name"} /></label><label>Meta description<textarea rows={3} maxLength={500} value={form.seoDescription} onChange={(e) => update("seoDescription", e.target.value)} /></label></section>
    </div><aside className="admin-editor-aside"><section className="admin-panel admin-form-panel"><h2>Publishing</h2><label>Status<select value={form.status} onChange={(e) => update("status", e.target.value as ProductInput["status"])}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label><p className="admin-muted">Drafts stay private. Published products appear in the store once saved.</p>{initial.id && initial.status === "PUBLISHED" && <Link href={`/products/${initial.slug}`} className="admin-text-link">View in storefront ↗</Link>}</section><section className="admin-panel admin-form-panel"><h2>Organisation</h2><label>Category<select value={form.categoryId ?? ""} onChange={(e) => update("categoryId", e.target.value ? Number(e.target.value) : null)}><option value="">Select category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{!categories.length && <Link className="admin-text-link" href="/admin/categories">Create your first category ↗</Link>}<label>Brand<select value={form.brandId ?? ""} onChange={(e) => update("brandId", e.target.value ? Number(e.target.value) : null)}><option value="">No brand</option>{brands.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{!brands.length && <Link className="admin-text-link" href="/admin/brands">Create a brand ↗</Link>}</section><section className="admin-editor-tip"><span>BEFORE YOU PUBLISH</span><p>Add a clear image, choose a category and check your price and stock counts.</p></section>{initial.id && <ArchiveButton id={initial.id} version={initial.version} />}</aside></div>
  </form>;
}
