import Link from "next/link";
import { notFound } from "next/navigation";
import { database, requireAdmin } from "@/lib/admin/auth";
import { TaxonomyForm } from "@/components/admin/controls";

export default async function Page({ params, searchParams }: { params: Promise<{ section: string }>; searchParams: Promise<{ page?: string }> }) {
  await requireAdmin(); const { section } = await params; const query = await searchParams;
  const page = Math.max(1, Math.min(100000, Number.parseInt(query.page ?? "1") || 1)); const db = database();
  if (section === "categories" || section === "brands") {
    const categories = await db.category.findMany({ where: { archivedAt: null }, include: { parent: true, _count: { select: { products: true } } }, orderBy: { name: "asc" } });
    const brands = section === "brands" ? await db.brand.findMany({ where: { archivedAt: null }, include: { _count: { select: { products: true } } }, orderBy: { name: "asc" } }) : [];
    const rows = section === "categories" ? categories.map((c) => ({ ...c, detail: c.parent?.name ?? "Top-level category" })) : brands.map((b) => ({ ...b, detail: "Brand" }));
    return <><div className="admin-heading"><div><span className="admin-eyebrow">ORGANISE YOUR CATALOGUE</span><h1>{section === "categories" ? "Categories" : "Brands"}</h1><p>Create the building blocks for your products.</p></div></div><div className="admin-taxonomy-grid"><section className="admin-panel"><div className="admin-panel-heading"><h2>{rows.length} {section}</h2></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Products</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td><strong>{r.name}</strong><small>{r.detail}</small></td><td>{r.slug}</td><td>{r._count.products}</td></tr>)}</tbody></table></div>{!rows.length && <div className="admin-empty"><h3>No {section} yet.</h3><p>Create your first {section === "categories" ? "category" : "brand"} using the form.</p></div>}</section><section className="admin-panel admin-form-panel"><h2>Add {section === "categories" ? "category" : "brand"}</h2><TaxonomyForm kind={section} categories={categories.map((c) => ({ id: c.id, name: c.name }))} /><p className="admin-muted">New entries are published and available to select in the product editor.</p></section></div></>;
  }
  if (section === "inventory") {
    const [rows, count] = await Promise.all([db.inventoryBalance.findMany({ where: { variant: { product: { archivedAt: null } } }, include: { variant: { include: { product: true } }, location: true }, take: 30, skip: (page - 1) * 30, orderBy: { updatedAt: "desc" } }), db.inventoryBalance.count({ where: { variant: { product: { archivedAt: null } } } })]);
    return <><div className="admin-heading"><div><span className="admin-eyebrow">READY FOR THE NEXT ORDER</span><h1>Inventory</h1><p>Physical stock, reservations and availability by location.</p></div></div><section className="admin-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Product / SKU</th><th>Location</th><th>On hand</th><th>Reserved</th><th>Available</th><th></th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td><strong>{r.variant.product.name}</strong><small>{r.variant.sku}</small></td><td>{r.location.name}</td><td>{r.onHand}</td><td>{r.reserved}</td><td><span className={`admin-badge ${r.onHand - r.reserved - r.safetyStock > 0 ? "published" : "draft"}`}>{Math.max(0, r.onHand - r.reserved - r.safetyStock)}</span></td><td><Link href={`/admin/products/${r.variant.productId}`} className="admin-text-link">Edit product ↗</Link></td></tr>)}</tbody></table></div>{!rows.length && <div className="admin-empty"><h3>No inventory yet.</h3><p>Add product variants and their stock to get started.</p></div>}<Pagination section={section} page={page} count={count} /></section></>;
  }
  if (section === "activity") {
    const [events, count] = await Promise.all([db.auditEvent.findMany({ include: { actor: true }, orderBy: { createdAt: "desc" }, take: 30, skip: (page - 1) * 30 }), db.auditEvent.count()]);
    return <><div className="admin-heading"><div><span className="admin-eyebrow">A CLEAR RECORD</span><h1>Activity log</h1><p>Who changed what, and when. Times shown in Australia/Sydney.</p></div></div><section className="admin-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Action</th><th>Record</th><th>Administrator</th><th>Time</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{event.action}</td><td>{event.entityType} #{event.entityId}</td><td>{event.actor?.firstName ?? "System"}</td><td>{event.createdAt.toLocaleString("en-AU", { timeZone: "Australia/Sydney" })}</td></tr>)}</tbody></table></div><Pagination section={section} page={page} count={count} /></section></>;
  }
  notFound();
}
function Pagination({ section, page, count }: { section: string; page: number; count: number }) { return <div className="admin-pagination"><span>{count} records · Page {page}</span><div>{page > 1 && <Link href={`/admin/${section}?page=${page - 1}`}>← Previous</Link>}{page * 30 < count && <Link href={`/admin/${section}?page=${page + 1}`}>Next →</Link>}</div></div>; }
