import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin, database } from "@/lib/admin/auth";
import { OrderActions } from "@/components/admin/order-actions";
import { smtpReady } from "@/lib/order-email";
export default async function Page({params}:{params:Promise<{id:string}>}) {
  const admin=await requireAdmin(); if(!admin.permissions.includes("orders.manage")) return <p>You do not have permission to manage orders.</p>;
  const {id}=await params; if(!/^\d+$/.test(id)) notFound();
  const order=await database().order.findUnique({where:{id:Number(id)},include:{items:true,notifications:true}}); if(!order) notFound();
  const address=order.shippingAddress as Record<string,string>; const policy=order.policySnapshot as Record<string,unknown> | null;
  return <><Link href="/admin/orders">All orders</Link><div className="admin-heading"><div><h1>{order.number}</h1><p>Manual order request · No payment collected by this website</p></div></div><div className="admin-editor-grid"><div><section className="admin-panel admin-form-panel"><h2>Customer & delivery</h2><p>{address.firstName} {address.lastName}</p><p>{order.email}</p><p>{address.phone}</p><p>{address.address}<br/>{address.city}, {address.region} {address.postcode}<br/>{address.country}</p><h3>Notes</h3><p style={{whiteSpace:"pre-wrap"}}>{String(policy?.notes || "No notes provided.")}</p></section><section className="admin-panel"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{order.items.map((item)=><tr key={item.id}><td><strong>{item.productName}</strong><small>{item.sku}</small><small>{(item.optionsSnapshot as {label?:string}|null)?.label}</small></td><td>{item.quantity}</td><td>{item.unitPrice.toFixed(2)}</td><td>{item.lineTotal.toFixed(2)}</td></tr>)}</tbody></table></div><div className="admin-form-panel"><p><strong>Items subtotal: AUD {order.subtotal.toFixed(2)}</strong></p><p>Delivery and final payable amount must be confirmed with the customer. Stock has not been reserved.</p></div></section></div><aside><section className="admin-panel"><OrderActions key={order.updatedAt.toISOString()} id={order.id} status={order.status} updatedAt={order.updatedAt.toISOString()}/></section><section className="admin-panel admin-form-panel"><h2>Email delivery</h2>{!smtpReady() && <p>SMTP is not configured. Emails are queued until you configure it and retry.</p>}{order.notifications.map((n)=><div key={n.id}><h3>{n.audience==="STORE"?"Store notification":"Customer acknowledgement"}</h3><p>{n.status} · {n.attempts} attempts</p>{n.lastError && <p>{n.lastError}</p>}</div>)}</section></aside></div></>;
}
