import Link from "next/link";
import { database, requireAdmin } from "@/lib/admin/auth";

export default async function Page() {
  const admin = await requireAdmin(); const db = database();
  const [total, published, drafts, variants, recent, activity] = await Promise.all([
    db.product.count({ where: { archivedAt: null } }), db.product.count({ where: { archivedAt: null, status: "PUBLISHED" } }),
    db.product.count({ where: { archivedAt: null, status: "DRAFT" } }), db.productVariant.count({ where: { isActive: true, product: { archivedAt: null } } }),
    db.product.findMany({ where: { archivedAt: null }, take: 5, orderBy: { updatedAt: "desc" }, include: { brand: true } }),
    db.auditEvent.findMany({ take: 5, orderBy: { createdAt: "desc" }, include: { actor: true } }),
  ]);
  return <><div className="admin-heading"><div><span className="admin-eyebrow">GET THINGS MOVING</span><h1>Store overview</h1><p>Welcome back, {admin.name.split(" ")[0]}. Here’s where your catalogue stands.</p></div><Link className="admin-button" href="/admin/products/new">+ Add product</Link></div><section className="admin-stats" aria-label="Catalogue statistics">{[["Total products",total,"Across your catalogue"],["Published",published,"Visible on the storefront"],["Drafts",drafts,"Ready for your attention"],["Active variants",variants,"Individual sellable SKUs"]].map(([label,count,detail]) => <article key={label}><span>{label}</span><strong>{count}</strong><small>{detail}</small></article>)}</section><div className="admin-overview-grid"><section className="admin-panel"><div className="admin-panel-heading"><h2>Recently updated products</h2><Link href="/admin/products">View all →</Link></div>{recent.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Product</th><th>Status</th><th>Price</th></tr></thead><tbody>{recent.map((p) => <tr key={p.id}><td><Link href={`/admin/products/${p.id}`}><strong>{p.name}</strong></Link></td><td><span className={`admin-badge ${p.status.toLowerCase()}`}>{p.status}</span></td><td>${Number(p.price).toFixed(2)}</td></tr>)}</tbody></table></div> : <div className="admin-empty"><span aria-hidden="true">▦</span><h3>Your next adventure starts here.</h3><p>Add your first product and bring your storefront to life.</p><Link className="admin-button" href="/admin/products/new">Create your first product →</Link></div>}</section><section className="admin-start-card"><span className="admin-eyebrow">A WELL-ORGANISED STORE</span><h2>Good gear.<br />Great foundations.</h2><p>Set up your categories, then add the products your riders are looking for.</p><Link href="/admin/categories">Manage categories <span>↗</span></Link></section></div><section className="admin-panel"><div className="admin-panel-heading"><h2>Recent activity</h2><Link href="/admin/activity">View history →</Link></div><div className="admin-activity-list">{activity.map((event) => <div key={event.id}><span className="admin-activity-icon">↗</span><p><strong>{event.action.replaceAll(".", " / ")}</strong><small>{event.actor?.firstName ?? "System"} · {event.entityType} #{event.entityId}</small></p><time>{event.createdAt.toLocaleString("en-AU", { timeZone: "Australia/Sydney", dateStyle: "medium", timeStyle: "short" })}</time></div>)}{!activity.length && <p className="admin-muted">Your store activity will appear here.</p>}</div></section></>;
}
