import type { Prisma } from "@/generated/prisma/client";
import Link from "next/link";
import { database, requireAdmin } from "@/lib/admin/auth";

export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  await requireAdmin(); const params = await searchParams;
  const q = (params.q ?? "").slice(0, 100), status = params.status;
  const page = Math.max(1, Math.min(100000, Number.parseInt(params.page ?? "1") || 1));
  const where: Prisma.ProductWhereInput = { archivedAt: status === "ARCHIVED" ? { not: null } : null, ...(status === "DRAFT" || status === "PUBLISHED" ? { status } : {}), ...(q ? { OR: [{ name: { contains: q } }, { variants: { some: { sku: { contains: q } } } }] } : {}) };
  const [products, count] = await Promise.all([database().product.findMany({ where, include: { brand: true, _count: { select: { variants: true } } }, orderBy: { updatedAt: "desc" }, take: 20, skip: (page - 1) * 20 }), database().product.count({ where })]);
  const url = (p: number) => `/admin/products?${new URLSearchParams({ q, status: status ?? "", page: String(p) })}`;
  return <><div className="admin-heading"><div><span className="admin-eyebrow">YOUR CATALOGUE</span><h1>Products <span className="admin-count">{count}</span></h1><p>Everything your riders need, all in one place.</p></div><Link href="/admin/products/new" className="admin-button">+ Add product</Link></div><section className="admin-panel"><form className="admin-list-filters"><input name="q" defaultValue={q} placeholder="Search products or SKUs…" aria-label="Search products or SKUs" /><select name="status" defaultValue={status ?? ""} aria-label="Product status"><option value="">All active products</option><option value="PUBLISHED">Published</option><option value="DRAFT">Drafts</option><option value="ARCHIVED">Archived</option></select><button className="admin-button secondary">Filter</button></form><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Product</th><th>Status</th><th>Price / AUD</th><th>Variants</th><th></th></tr></thead><tbody>{products.map((p) => <tr key={p.id}><td><strong>{p.name}</strong><small>/{p.slug}</small></td><td><span className={`admin-badge ${p.archivedAt ? "draft" : p.status.toLowerCase()}`}>{p.archivedAt ? "Archived" : p.status}</span></td><td>${Number(p.price).toFixed(2)}</td><td>{p._count.variants}</td><td>{!p.archivedAt && <Link className="admin-text-link" href={`/admin/products/${p.id}`}>Edit ↗</Link>}</td></tr>)}</tbody></table></div>{!products.length && <div className="admin-empty"><h3>{q || status ? "No products match these filters." : "Your catalogue is ready for its first product."}</h3><p>Add a product or adjust your search to get started.</p></div>}<div className="admin-pagination"><span>{count} products · Page {page}</span><div>{page > 1 && <Link href={url(page - 1)}>← Previous</Link>}{page * 20 < count && <Link href={url(page + 1)}>Next →</Link>}</div></div></section></>;
}
